### ISSUE TITLE
Audio not working with ZzFX Sound Caching

### ISSUE THREAD

**Issue by jdnichollsc** [keithclark/ZzFXM#24]
Hello mate,

I was testing again this feature from GitHub page using Chrome but I'm not getting audio:
```

const lazer = zzfxG(...[1.04,,60,.01,.09,.44,,1.61,-5.2,,,,,.3,,.1,,.87,.09]);
zzfxP(lazer);
```

I can see this warning from GitHub page:
`The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.`

What do you think?
Thanks in advance for your help!

**Comment by keithclark** [comment]
Modern browsers won't play audio until the user has interacted with the page. Try starting a song on the demo page and, while it's playing, run your code in the console. If all goes well you should hear the sound play with the song.

Also, the Github demo page suspends the audio context when a song isn't playing to reduce system resources. You can resume it using `zzfxX.resume()` if you want to hear your sounds without a song playing. Rather than fighting against these issues, it might be better to just create yourself a simple HTML document for testing.

**Comment by jdnichollsc** [comment]
Awesome, thanks for sharing that!!

It's working from Codepen with a little change: codepen.io/jdnichollsc/pen/KKMRPrr

Thanks for your comments, have a nice Halloween mate!
