### ISSUE TITLE
zzfxR API does not work?

### ISSUE THREAD

**Issue by octogonz** [keithclark/ZzFXM#29]
The API appears to provide a way to adjust the sampling rate:

https://github.com/keithclark/ZzFXM/blob/9f90e98dbc2b42e78bcfdc2252f9da2d8196025b/zzfx.js#L13-L14

...however when I reduce this variable, the song plays more slowly and the pitches are lower.

Is there a way to play a song at a different rate without affecting how it sounds?  

(The problem I'm trying to solve is that generating a large buffer consumes too much CPU time.)

**Comment by keithclark** [comment]
You need to set `zzfxR` before you call any of the other zzfx methods. If you open the [demo page](https://keithclark.github.io/ZzFXM/), start devtools and run this in the console you'll set the sample rate to 22050hz:

```
zzfxR = 22050
```

If you now click "play" zzfxm will generate a 22050hz version of the song and play it back at that sample rate. Now stop the song and set run:

```
zzfxR = 44100
```

Now click play on the same song again. It will now play at double speed because it was generated at 22050hz but is playing at 44100hz.

For performance reasons the demo page caches the last generated song. If you start and stop another example on the page to clear the cache and then play the original song again it should now be regenerated and play at 44100hz.

Does that help?

**Comment by octogonz** [comment]
Yes, thanks!  It was my fault, the way I was bundling the library caused `zzfxR` to get assigned after the sound was rendered, as you had guessed.
