### ISSUE TITLE
Instrument with frequency=220Hz does not play

### ISSUE THREAD

**Issue by octogonz** [keithclark/ZzFXM#30]
## Repro steps:

1. Open [Cuddly Demos](https://keithclark.github.io/ZzFXM/tracker/?url=https://raw.githubusercontent.com/keithclark/ZzFXM/master/examples/songs/cuddly.js) in the Tracker
2. Change `Instrument 0` frequency to `220`
3. Confirm that the song plays in the tracker
4. Generate source code, and try playing it using the JavaScript engine -- it sounds very wrong because most notes are muted

## Investigation

The `zzfx()` frequency parameter defaults to `220`.  When the Tracker serializes a song, it omits `220`in the sparse array, as it does for all default values.

However, when `zzfxm()` calculates the pitch for a note, it does not assign this default value:

https://github.com/keithclark/ZzFXM/blob/cb07fa9ca36aefd67a0c8c656d2958b62f8ed9fe/zzfxm.js#L111-L116

Thus the frequency passed to `zzfx()` ends up being `undefined * pitch` which is `NaN`.

It seems that either:
1. `zzfxm()` needs to apply this default before adjusting the pitch; OR
2. we should document that this parameter is required for song instruments (i.e. its spec is different from `zzfx()` sounds), and therefore the tracker must never omit `220`

#2 seems like the better choice; adding more code to the player is less desirable than eliminating an optimization that never actually worked.

**Comment by keithclark** [comment]
Nice find! Looking back through the commit history, this has been around forever.

I agree that #2 is the better option as it's one less magic number to include in the player and that value is unlikely to be used by the majority of songs.

The fix should be as simple as updating the `encode` method of `zzfxm-song-encoder` package so that it doesn't strip that value: https://github.com/keithclark/ZzFXM/blob/ba70ce57c5d5ff1af7a674f468e32a7b72be9195/tools/local_modules/zzfxm-song-encoder/encode.js#L57-L59

 The `decode` method should probably stay as-is so that existing songs will still load but will be correctly encoded when saved.

The song-encoder is shared by the various apps/tools so it should fix the MOD convertor and packer too 😄

**Comment by octogonz** [comment]
Here's a PR: https://github.com/keithclark/ZzFXM/pull/31

**Comment by octogonz** [comment]
(I wasn't sure how to regenerate `zzfxm.min.js` however.)

**Comment by keithclark** [comment]
Thanks for the PR. Unfortunately the graphics card in my iMac died a couple of days ago so I need to get a dev env. set up before I can test the changes.

You shouldn't need to regenerate `ZzFXM.min.js` as your changes only impact the song generation tools, not the playback routine.

I have changes of my own in a `tracker-dev` branch that I want to get deployed so I'll merge these together and release new versions of the various tools.
